source "https://rubygems.org"

gem "fastlane"

source 'https://rubygems.org' do
  gem 'cocoapods', '~> 1.0'
  gem 'xcodeproj', :git => 'https://github.com/CocoaPods/Xcodeproj.git', :branch => 'master' 
end