# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

use_frameworks!

def google_utilites
  pod 'GoogleUtilities/AppDelegateSwizzler'
  pod 'GoogleUtilities/Environment'
  pod 'GoogleUtilities/ISASwizzler'
  pod 'GoogleUtilities/Logger'
  pod 'GoogleUtilities/MethodSwizzler'
  pod 'GoogleUtilities/NSData+zlib'
  pod 'GoogleUtilities/Network'
  pod 'GoogleUtilities/Reachability'
  pod 'GoogleUtilities/UserDefaults'
  pod 'GTMSessionFetcher'
end

target 'Authentication' do
  # Comment the next line if you don't want to use dynamic frameworks
  google_utilites
  pod 'Firebase/Auth'
inherit! :search_paths
  # Pods for Authentication
  pod 'SharedAuthentication', :path => '../../shared/SharedAuthentication'
  
target 'AuthenticationTests' do
    # Pods for testing
    
  end

end

target 'Backend' do
  google_utilites
  # Comment the next line if you don't want to use dynamic frameworks
inherit! :search_paths
  # Pods for Authentication
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'FirebaseFirestoreSwift'

end

target 'Dashboard' do
  google_utilites
  # Comment the next line if you don't want to use dynamic frameworks
inherit! :search_paths
pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'FirebaseFirestoreSwift'
  # Pods for Authentication
target 'DashboardTests' do
    # Pods for testing
    
  end

end

target 'Creation' do
  # Comment the next line if you don't want to use dynamic frameworks
inherit! :search_paths
  # Pods for Authentication

end

target 'KotlinIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
google_utilites
inherit! :search_paths
  # Pods for KotlinIOS
  pod 'Swinject'
  target 'KotlinIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KotlinIOSUITests' do
    # Pods for testing
  end

end
